server:
  port: 8082

spring:
  application:
    name: comment-service
  main:
    allow-bean-definition-overriding: true
  zipkin:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      uri: mongodb://localhost:27017/school
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka